---
version: "3.0"
  
services:
  
  nginx:
    build: nginx
    links:
      - apache:apache
    ports:
      - "80:80"
  
  varnish:
    build: varnish
    links:
      - apache:apache
  
  apache:
    build: Apache
    links:
      - phpfpm:phpfpm
    volumes:
      - volweb:/var/www
  
  phpfpm:
    build: php5
    links:
      - memcached:memcached
    volumes:
      - volweb:/var/www
  
  memcached:
    build: memcached
  
  
  mariadb:
    build: MariaDB
    volumes:
      - volmaria:/var/lib/mysql
    env_file:
      - mariadb.env
  
volumes:
  volmaria:
  volweb:
...
