---

nginx:
  build: nginx
  links:
    - apache
  ports:
    - "80:80"

varnish:
  build: varnish
  links:
    - apache

apache:
  build: Apache
  links:
    - phpfpm

phpfpm:
  build: php5
  links:
    - memcached

memcached:
  build: memcached
  links:
    - mariadb


mariadb:
  build: MariaDB
  volumes:
    - volmaria:/var/lib/mysql

...

