version: "3.0"
  
services:
  
  nginx:
    build: nginx
    networks:
      hlc-docker:
        ipv4_address: 192.168.250.10
    links:
      - apache
    ports:
      - "80:80"
  
  varnish:
    build: varnish
    networks:
      hlc-docker:
        ipv4_address: 192.168.250.20
    links:
      - apache
  
  apache:
    build: Apache
    networks:
      hlc-docker:
        ipv4_address: 192.168.250.30
    links:
      - phpfpm
    volumes:
      - volweb:/var/www
  
  phpfpm:
    build: php5
    networks:
      hlc-docker:
        ipv4_address: 192.168.250.40
    links:
      - memcached
      - mariadb
    volumes:
      - volweb:/var/www
  
  memcached:
    build: memcached
    networks:
      hlc-docker:
        ipv4_address: 192.168.250.50
    links:
      - mariadb
  
  
  mariadb:
    build: MariaDB
    networks:
      hlc-docker:
        ipv4_address: 192.168.250.60
    volumes:
      - volmaria:/var/lib/mysql
    env_file:
      - mariadb.env
  
networks:
  hlc-docker:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.250.0/24

volumes:
  volmaria:
  volweb:
