#!/bin/bash

ipdir=$APACHE2_PORT_80_TCP_ADDR

sed -i "s/IPAPACHE/$ipdir/g" /etc/nginx/conf.d/default.conf

service nginx start
sleep 2
sleep 300
SPID=$(pidof nginx)
while [[ ! -z $SPID ]]; do
        sleep 5
        SPID=$(pidof nginx)
done;
