#!/bin/bash

ipdir=$(dig +short apache)

sed -i "s/IPVARNISH/$ipdir/g" /etc/nginx/sites-available/default

service nginx start
sleep 2
sleep 300
SPID=$(pidof nginx)
while [[ ! -z $SPID ]]; do
        sleep 5
        SPID=$(pidof nginx)
done;
